apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
metadata:
  namespace: local
  name: demo

export:
  storage:
    type: jumpstarter_driver_sdmux.driver.UsbSdMux

  power:
    type: jumpstarter_driver_gpiod.driver.DigitalOutput
    config:
      line: 5
      active_low: true
